name: Build and push Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_version: 2.24.12
          nix_conf: |
            substituters = https://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            system-features = benchmark big-parallel kvm nixos-test

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@f68581e27a06c8c9115dec37e42325d562d9664b
        with:
          primary-key: nix-docker-${{ matrix.os }}-${{ hashFiles('nix/docker.nix', 'nix/pkgs.nix') }}
          restore-prefixes-first-match: nix-docker-${{ matrix.os }}-
          gc-max-store-size: 4G

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load image
        run: |
          set -euox pipefail
          IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository }}/web-server"
          IMAGE_PATH="$(nix-build --no-out-link --argstr name $IMAGE_NAME nix/docker.nix)"
          IMAGE_NAME_WITH_TAG="$(docker load -i $IMAGE_PATH | sed -r 's/Loaded image: (.*)/\1/')"
          echo "IMAGE_NAME_WITH_TAG=$IMAGE_NAME_WITH_TAG" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"

      - name: Push image
        run: |
          set -euox pipefail
          docker tag "$IMAGE_NAME_WITH_TAG" "$IMAGE_NAME:latest"
          docker push --all-tags "$IMAGE_NAME"
