name: nix-build

on:
  push:
  pull_request:

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-13, macos-14] # TODO: add macos-15 once "Install Nix"-step works
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix-build

